title: "A-SMART Lab"
description: "Applied Systems Modeling, Analytics, Research & Technology (A-SMART) Lab"
theme: minima

header_pages:
  - PI.md
  - people.md
  - research.md
  - projects.md
  - publications.md
  - collaborators.md
  - sponsors.md
